server:
  port: 8083

spring:
  application:
    name: audit-service
  datasource:
    url: jdbc:h2:mem:auditdb
    driverClassName: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  autoconfigure:
    exclude: org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 2s
          multiplier: 2.0
          max-interval: 10s
          max-retries: 3
        default-requeue-rejected: false

app:
  jwt:
    secret: ${JWT_SECRET}
    expiry: ${JWT_EXPIRY}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@localhost:8761/eureka/