apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: lab5-api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_HOST
              value: "discovery-server"
            - name: EUREKA_PORT
              value: "8761"
            - name: EUREKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: saas-secrets
                  key: EUREKA_USERNAME
            - name: EUREKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: saas-secrets
                  key: EUREKA_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080