server:
  servlet:
    context-path: /api

app:
  jwt:
    secret: ${JWT_SECRET}
    expiry: ${JWT_EXPIRY}
  refresh:
    expiry: ${ACCESS_EXPIRY}
  frontend:
    url: ${FRONTEND_URL}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_EMAIL}
    password: ${SMTP_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

stripe:
  api-key: ${STRIPE_SECRET}
  webhook-secret: ${WEBHOOK_SECRET}