services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: saas-rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - saas-network

  redis:
    image: redis:8-alpine
    container_name: saas-redis
    ports:
      - "${REDIS_PORT}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - saas-network

  discovery-server:
    build:
      context: .
      dockerfile: discovery-server/Dockerfile
    container_name: saas-discovery
    ports:
      - "${EUREKA_PORT}:8761"
    environment:
      SPRING_SECURITY_USER_NAME: ${EUREKA_USERNAME}
      SPRING_SECURITY_USER_PASSWORD: ${EUREKA_PASSWORD}
    networks:
      - saas-network

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: saas-gateway
    ports:
      - "${GATEWAY_PORT}:8080"
    environment:
      EUREKA_HOST: discovery-server
      EUREKA_PORT: 8761
      EUREKA_USERNAME: ${EUREKA_USERNAME}
      EUREKA_PASSWORD: ${EUREKA_PASSWORD}
    depends_on:
      - discovery-server
    networks:
      - saas-network

  iam-service:
    build:
      context: .
      dockerfile: iam-service/Dockerfile
    container_name: saas-iam
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRY: ${JWT_EXPIRY}
      ACCESS_EXPIRY: ${ACCESS_EXPIRY}
      EUREKA_HOST: discovery-server
      EUREKA_PORT: 8761
      EUREKA_USERNAME: ${EUREKA_USERNAME}
      EUREKA_PASSWORD: ${EUREKA_PASSWORD}
    depends_on:
      - discovery-server
      - rabbitmq
      - redis
    networks:
      - saas-network

  organization-service:
    build:
      context: .
      dockerfile: organization-service/Dockerfile
    container_name: saas-organization
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRY: ${JWT_EXPIRY}
      EUREKA_HOST: discovery-server
      EUREKA_PORT: 8761
      EUREKA_USERNAME: ${EUREKA_USERNAME}
      EUREKA_PASSWORD: ${EUREKA_PASSWORD}
    depends_on:
      - discovery-server
      - rabbitmq
      - redis
    networks:
      - saas-network

  billing-service:
    build:
      context: .
      dockerfile: billing-service/Dockerfile
    container_name: saas-billing
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRY: ${JWT_EXPIRY}
      FRONTEND_URL: ${FRONTEND_URL}
      STRIPE_SECRET: ${STRIPE_SECRET}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      EUREKA_HOST: discovery-server
      EUREKA_PORT: 8761
      EUREKA_USERNAME: ${EUREKA_USERNAME}
      EUREKA_PASSWORD: ${EUREKA_PASSWORD}
    depends_on:
      - discovery-server
      - rabbitmq
      - redis
    networks:
      - saas-network

  analysis-service:
    build:
      context: .
      dockerfile: analysis-service/Dockerfile
    container_name: saas-analysis
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRY: ${JWT_EXPIRY}
      EUREKA_HOST: discovery-server
      EUREKA_PORT: 8761
      EUREKA_USERNAME: ${EUREKA_USERNAME}
      EUREKA_PASSWORD: ${EUREKA_PASSWORD}
    depends_on:
      - discovery-server
      - rabbitmq
    networks:
      - saas-network

  audit-service:
    build:
      context: .
      dockerfile: audit-service/Dockerfile
    container_name: saas-audit
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRY: ${JWT_EXPIRY}
      EUREKA_HOST: discovery-server
      EUREKA_PORT: 8761
      EUREKA_USERNAME: ${EUREKA_USERNAME}
      EUREKA_PASSWORD: ${EUREKA_PASSWORD}
    depends_on:
      - discovery-server
      - rabbitmq
    networks:
      - saas-network

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    container_name: saas-notification
    environment:
      SMTP_EMAIL: ${SMTP_EMAIL}
      SMTP_KEY: ${SMTP_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      EUREKA_HOST: discovery-server
      EUREKA_PORT: 8761
      EUREKA_USERNAME: ${EUREKA_USERNAME}
      EUREKA_PASSWORD: ${EUREKA_PASSWORD}
    depends_on:
      - discovery-server
      - rabbitmq
    networks:
      - saas-network

networks:
  saas-network:
    driver: bridge