server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                maxAge: 3600
          discovery:
            locator:
              enabled: true
          routes:
            - id: iam-service-route
              uri: lb://iam-service
              order: 1
              predicates:
                - Path=/api/auth/**, /api/users/**, /api/organizations/*/members/**
              filters:
                - StripPrefix=1

            - id: audit-service-route
              uri: lb://audit-service
              order: 1
              predicates:
                - Path=/api/organizations/*/audit/**
              filters:
                - StripPrefix=1

            - id: organization-service-route
              uri: lb://organization-service
              order: 1
              predicates:
                - Path=/api/organizations, /api/organizations/{id}
              filters:
                - StripPrefix=1

            - id: core-monolith-route
              uri: lb://core-monolith
              order: 2
              predicates:
                - Path=/api/organizations/**
              filters:
                - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME:admin}:${EUREKA_PASSWORD:admin}@localhost:8761/eureka/